#!/usr/bin/env python3
# Path: utility/make_linker_script.py

import argparse
import os
import sys

try:
    from .make_lyn_reference import format_address, iter_export_symbols, sorted_symbols
except ImportError:
    from make_lyn_reference import format_address, iter_export_symbols, sorted_symbols


def write_linker_script(outfile, symbols, source_name, snapshot):
    outfile.write(f"/* Generated by {os.path.basename(sys.argv[0])} */\n")
    outfile.write(f"/* Extracted from {source_name} */\n")
    if snapshot:
        outfile.write(f"/* Snapshot: {snapshot} */\n")
    outfile.write("/* Do not edit by hand. */\n\n")

    for symbol in symbols:
        outfile.write(f"{symbol.name} = {format_address(symbol.address)};\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('infile', type=argparse.FileType('rb'), help='ELF file to extract symbols from')
    parser.add_argument('outfile', nargs='?', type=argparse.FileType('w'), default=sys.stdout, help='Output linker script')
    parser.add_argument('--snapshot', default='', help='Optional snapshot label to include in output comments')
    args = parser.parse_args()

    conflicts = []
    symbols = sorted_symbols(
        iter_export_symbols(
            args.infile,
            include_local=True,
            on_conflict=lambda name, candidates: conflicts.append((name, candidates)),
        )
    )
    if not symbols:
        parser.error('no exportable symbols found')

    write_linker_script(
        args.outfile,
        symbols,
        os.path.basename(args.infile.name),
        args.snapshot,
    )
    print(
        f"Extracted {len(symbols)} symbols; skipped {len(conflicts)} ambiguous names",
        file=sys.stderr,
    )

if __name__ == '__main__':
    main()
