#!/usr/bin/env python3
# Path: utility/make_lyn_reference.py

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

FUNCTION_TYPES = {"STT_FUNC"}
DATA_TYPES = {"STT_OBJECT", "STT_COMMON", "STT_NOTYPE"}
GLOBAL_BINDS = {"STB_GLOBAL", "STB_WEAK"}


@dataclass(frozen=True)
class ExportSymbol:
    name: str
    address: int
    kind: str


def is_exportable_name(name):
    return bool(re.match(r"^[A-Za-z_][A-Za-z0-9_.$]*$", name)) and not name.startswith(".")


def normalized_name(name):
    return name.replace(".", "_")


def symbol_kind(symbol):
    symbol_type = symbol["st_info"]["type"]
    if symbol_type in FUNCTION_TYPES:
        return "func"
    if symbol_type in DATA_TYPES:
        return "data"
    return None


def iter_export_symbols(elf_file, include_local=False):
    from elftools.elf.elffile import ELFFile

    elf = ELFFile(elf_file)
    seen = set()

    for section in elf.iter_sections():
        if section["sh_type"] != "SHT_SYMTAB":
            continue

        for symbol in section.iter_symbols():
            name = normalized_name(symbol.name)
            address = symbol["st_value"]

            if not name or address == 0 or name in seen or not is_exportable_name(name):
                continue

            bind = symbol["st_info"]["bind"]
            if not include_local and bind not in GLOBAL_BINDS:
                continue

            kind = symbol_kind(symbol)
            if kind is None:
                continue

            seen.add(name)
            yield ExportSymbol(name=name, address=address, kind=kind)


def sorted_symbols(symbols):
    return sorted(symbols, key=lambda symbol: (symbol.address, symbol.name))


def write_lyn_reference(outfile, symbols, source_name, snapshot):
    outfile.write(f"@ Generated by {os.path.basename(sys.argv[0])}\n")
    outfile.write(f"@ Extracted from {source_name}\n")
    if snapshot:
        outfile.write(f"@ Snapshot: {snapshot}\n")
    outfile.write("@ Do not edit by hand.\n\n")

    outfile.write(".macro SET_FUNC name, value\n")
    outfile.write("    .global \\name\n")
    outfile.write("    .type   \\name, function\n")
    outfile.write("    .set    \\name, \\value\n")
    outfile.write(".endm\n\n")

    outfile.write(".macro SET_DATA name, value\n")
    outfile.write("    .global \\name\n")
    outfile.write("    .type   \\name, object\n")
    outfile.write("    .set    \\name, \\value\n")
    outfile.write(".endm\n\n")

    for symbol in symbols:
        macro = "SET_FUNC" if symbol.kind == "func" else "SET_DATA"
        outfile.write(f"{macro} {symbol.name}, 0x{symbol.address:08X}\n")


def write_ea_defines(outfile, symbols, source_name, snapshot):
    outfile.write(f"// Generated by {os.path.basename(sys.argv[0])}\n")
    outfile.write(f"// Extracted from {source_name}\n")
    if snapshot:
        outfile.write(f"// Snapshot: {snapshot}\n")
    outfile.write("// Do not edit by hand.\n\n")

    width = max((len(symbol.name) for symbol in symbols), default=0)
    for symbol in symbols:
        outfile.write(f"#define {symbol.name.ljust(width)} 0x{symbol.address:08X}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Generate lyn reference and Event Assembler symbol files from a decomp ELF."
    )
    parser.add_argument("infile", type=argparse.FileType("rb"), help="ELF file to extract symbols from")
    parser.add_argument("--lyn-reference", type=Path, help="Output lyn/FE-CLib reference .s file")
    parser.add_argument("--ea-defines", type=Path, help="Output Event Assembler #define include file")
    parser.add_argument("--snapshot", default="", help="Optional snapshot label to include in output comments")
    parser.add_argument("--include-local", action="store_true", help="Include local symbols, not only global/weak symbols")
    args = parser.parse_args()

    if not args.lyn_reference and not args.ea_defines:
        parser.error("at least one of --lyn-reference or --ea-defines is required")

    symbols = sorted_symbols(iter_export_symbols(args.infile, args.include_local))
    if not symbols:
        parser.error("no exportable symbols found")

    source_name = os.path.basename(args.infile.name)

    if args.lyn_reference:
        with args.lyn_reference.open("w", newline="\n") as outfile:
            write_lyn_reference(outfile, symbols, source_name, args.snapshot)

    if args.ea_defines:
        with args.ea_defines.open("w", newline="\n") as outfile:
            write_ea_defines(outfile, symbols, source_name, args.snapshot)

    print(f"Extracted {len(symbols)} symbols", file=sys.stderr)


if __name__ == "__main__":
    main()
